# Generated by Django 2.2 on 2019-04-12 18:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('usuario', '0006_auto_20190411_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hilos_Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('fecha_publicado', models.DateTimeField(default=datetime.datetime.now)),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comments.Comments')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario')),
            ],
        ),
    ]
