# Generated by Django 2.2 on 2019-04-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaccion',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
