# Generated by Django 2.2 on 2019-04-11 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_publicado',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
