# Generated by Django 2.2 on 2019-04-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0004_auto_20190411_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField(default=False)),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seguidor_requests_created', to='usuario.Usuario')),
                ('id_perfil_seguido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario')),
            ],
        ),
    ]
