# Generated by Django 2.2 on 2019-04-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publicacion.Publicacion')),
            ],
        ),
    ]
